# Generated by Django 5.2.8 on 2025-11-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0003_remove_team_is_default_home_team_is_home_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="大会名"
                    ),
                ),
                ("game_datetime", models.DateTimeField(verbose_name="試合日時")),
                (
                    "ballpark",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="球場名"
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "晴れ"),
                            ("cloudy", "曇り"),
                            ("rain", "雨"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="天候",
                    ),
                ),
                (
                    "first_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_batting_games",
                        to="teams.team",
                        verbose_name="先攻チーム",
                    ),
                ),
                (
                    "second_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_batting_games",
                        to="teams.team",
                        verbose_name="後攻チーム",
                    ),
                ),
            ],
        ),
    ]
