# Generated by Django 5.2.8 on 2025-11-27 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="大会名"
                    ),
                ),
                ("game_datetime", models.DateTimeField(verbose_name="試合日時")),
                (
                    "ballpark",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="球場"
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "晴れ"),
                            ("cloudy", "曇り"),
                            ("rain", "雨"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="天候",
                    ),
                ),
                ("lineup_json", models.JSONField(blank=True, default=dict)),
                (
                    "first_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_batting_games",
                        to="teams.team",
                        verbose_name="先攻チーム",
                    ),
                ),
                (
                    "second_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_batting_games",
                        to="teams.team",
                        verbose_name="後攻チーム",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField(verbose_name="イニング")),
                ("is_top", models.BooleanField(default=True, verbose_name="表攻撃")),
                (
                    "result",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="結果"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="打席順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batter_scores",
                        to="players.player",
                        verbose_name="打者",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="games.game",
                        verbose_name="試合",
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitcher_scores",
                        to="players.player",
                        verbose_name="投手",
                    ),
                ),
            ],
            options={
                "verbose_name": "スコア",
                "verbose_name_plural": "スコア一覧",
                "ordering": ["game", "inning", "is_top", "order"],
            },
        ),
        migrations.CreateModel(
            name="Inning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="イニング番号"),
                ),
                ("is_top", models.BooleanField(default=True, verbose_name="表攻撃")),
                ("runs", models.PositiveSmallIntegerField(default=0)),
                ("outs", models.PositiveSmallIntegerField(default=0)),
                ("current_batter", models.PositiveSmallIntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="games.game",
                        verbose_name="試合",
                    ),
                ),
            ],
            options={
                "verbose_name": "イニング",
                "verbose_name_plural": "イニング一覧",
                "ordering": ["game", "number", "is_top"],
                "unique_together": {("game", "number", "is_top")},
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batting_order",
                    models.PositiveSmallIntegerField(verbose_name="打順（1〜9）"),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "投手"),
                            (2, "捕手"),
                            (3, "一塁手"),
                            (4, "二塁手"),
                            (5, "三塁手"),
                            (6, "遊撃手"),
                            (7, "左翼手"),
                            (8, "中堅手"),
                            (9, "右翼手"),
                        ],
                        verbose_name="守備位置（1〜9）",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="games.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineup_entries",
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "メンバー表（打順）",
                "verbose_name_plural": "メンバー表一覧",
                "ordering": ["game", "team", "batting_order"],
                "unique_together": {("game", "team", "batting_order")},
            },
        ),
    ]
