# Generated by Django 5.2.8 on 2025-11-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="大会名"
                    ),
                ),
                ("game_datetime", models.DateTimeField(verbose_name="試合日時")),
                (
                    "ballpark",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="球場名"
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "晴れ"),
                            ("cloudy", "曇り"),
                            ("rain", "雨"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="天候",
                    ),
                ),
                (
                    "first_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_batting_games",
                        to="teams.team",
                        verbose_name="先攻チーム",
                    ),
                ),
                (
                    "second_batting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_batting_games",
                        to="teams.team",
                        verbose_name="後攻チーム",
                    ),
                ),
            ],
            options={
                "verbose_name": "試合",
                "verbose_name_plural": "試合一覧",
                "ordering": ["-game_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Inning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="回")),
                (
                    "is_top",
                    models.BooleanField(default=True, verbose_name="表かどうか"),
                ),
                (
                    "top_bottom",
                    models.CharField(
                        choices=[("top", "表"), ("bottom", "裏")],
                        default="top",
                        max_length=10,
                    ),
                ),
                ("runs", models.PositiveSmallIntegerField(default=0)),
                ("outs", models.PositiveSmallIntegerField(default=0)),
                ("current_batter", models.PositiveSmallIntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "イニング",
                "verbose_name_plural": "イニング一覧",
                "ordering": ["game", "number", "is_top"],
                "unique_together": {("game", "number", "is_top")},
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batting_order",
                    models.PositiveSmallIntegerField(verbose_name="打順（1〜9）"),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "投手"),
                            (2, "捕手"),
                            (3, "一塁手"),
                            (4, "二塁手"),
                            (5, "三塁手"),
                            (6, "遊撃手"),
                            (7, "左翼手"),
                            (8, "中堅手"),
                            (9, "右翼手"),
                        ],
                        verbose_name="守備位置（1〜9）",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="games.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineup_entries",
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "メンバー表（打順）",
                "verbose_name_plural": "メンバー表一覧",
                "ordering": ["game", "team", "batting_order"],
                "unique_together": {("game", "team", "batting_order")},
            },
        ),
    ]
