# Generated by Django 5.2.8 on 2025-11-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("players", "0002_alter_player_options"),
        ("teams", "0004_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "試合", "verbose_name_plural": "試合一覧"},
        ),
        migrations.CreateModel(
            name="Inning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="回")),
                ("is_top", models.BooleanField(default=True, verbose_name="表")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "number", "is_top"],
                "unique_together": {("game", "number", "is_top")},
            },
        ),
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="球数")),
                (
                    "pitch_result",
                    models.CharField(
                        choices=[
                            ("Ball", "Ball"),
                            ("StrikeSwing", "Strike (Swing)"),
                            ("StrikeLook", "Strike (Looking)"),
                            ("Foul", "Foul"),
                            ("InPlay", "In Play"),
                        ],
                        max_length=20,
                        verbose_name="投球結果",
                    ),
                ),
                (
                    "batter_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("None", "No result"),
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Triple", "Triple"),
                            ("HomeRun", "Home Run"),
                            ("Walk", "Walk"),
                            ("Strikeout", "Strikeout"),
                            ("Out", "Out"),
                        ],
                        default="None",
                        max_length=20,
                        verbose_name="打者結果",
                    ),
                ),
                (
                    "runs_scored",
                    models.PositiveSmallIntegerField(default=0, verbose_name="得点"),
                ),
                (
                    "batter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pitches_batted",
                        to="players.player",
                    ),
                ),
                (
                    "inning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="games.inning",
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pitches_pitched",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["inning", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batting_order",
                    models.PositiveSmallIntegerField(verbose_name="打順"),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (1, "投手"),
                            (2, "捕手"),
                            (3, "一塁手"),
                            (4, "二塁手"),
                            (5, "三塁手"),
                            (6, "遊撃手"),
                            (7, "左翼手"),
                            (8, "中堅手"),
                            (9, "右翼手"),
                        ],
                        verbose_name="守備位置 (1〜9)",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="games.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineup_entries",
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "team", "batting_order"],
                "unique_together": {("game", "team", "batting_order")},
            },
        ),
    ]
