# Generated by Django 5.2.8 on 2025-11-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lineup_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
