# Generated by Django 5.2.8 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_options_inning_pitch_lineup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineup",
            options={
                "ordering": ["game", "team", "batting_order"],
                "verbose_name": "メンバー表（1打順）",
                "verbose_name_plural": "メンバー表一覧",
            },
        ),
        migrations.AlterField(
            model_name="lineup",
            name="batting_order",
            field=models.PositiveSmallIntegerField(verbose_name="打順（1〜9）"),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="position",
            field=models.IntegerField(
                choices=[
                    (1, "投手"),
                    (2, "捕手"),
                    (3, "一塁手"),
                    (4, "二塁手"),
                    (5, "三塁手"),
                    (6, "遊撃手"),
                    (7, "左翼手"),
                    (8, "中堅手"),
                    (9, "右翼手"),
                ],
                verbose_name="守備位置（1〜9）",
            ),
        ),
    ]
