# Generated by Django 5.2.8 on 2025-11-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_lineup_json"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={},
        ),
        migrations.RemoveField(
            model_name="game",
            name="lineup_json",
        ),
    ]
