# Generated by Django 5.2.8 on 2025-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_lineup_options_alter_lineup_batting_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["-game_datetime"],
                "verbose_name": "試合",
                "verbose_name_plural": "試合一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="inning",
            options={
                "ordering": ["game", "number", "is_top"],
                "verbose_name": "イニング",
                "verbose_name_plural": "イニング一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="lineup",
            options={
                "ordering": ["game", "team", "batting_order"],
                "verbose_name": "メンバー表（打順）",
                "verbose_name_plural": "メンバー表一覧",
            },
        ),
        migrations.AlterField(
            model_name="inning",
            name="is_top",
            field=models.BooleanField(default=True, verbose_name="表かどうか"),
        ),
        migrations.DeleteModel(
            name="Pitch",
        ),
    ]
