# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_options_remove_game_lineup_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lineup_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
