# Generated by Django 5.2.8 on 2025-11-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_options_alter_inning_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inning",
            name="top_bottom",
            field=models.CharField(
                choices=[("top", "表"), ("bottom", "裏")], default="top", max_length=10
            ),
        ),
    ]
