# Generated by Django 5.2.8 on 2025-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_inning_top_bottom"),
    ]

    operations = [
        migrations.AddField(
            model_name="inning",
            name="current_batter",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="inning",
            name="outs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inning",
            name="runs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
