# Generated by Django 5.2.8 on 2025-11-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "default_position",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "投手"),
                            (2, "捕手"),
                            (3, "一塁手"),
                            (4, "二塁手"),
                            (5, "三塁手"),
                            (6, "遊撃手"),
                            (7, "左翼手"),
                            (8, "中堅手"),
                            (9, "右翼手"),
                        ],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "選手",
                "verbose_name_plural": "選手一覧",
            },
        ),
    ]
