# Generated by Django 5.2.8 on 2025-11-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "選手", "verbose_name_plural": "選手一覧"},
        ),
    ]
