# Generated by Django 5.2.8 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("is_home_team", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "チーム",
                "verbose_name_plural": "チーム一覧",
            },
        ),
    ]
