# Generated by Django 5.2.8 on 2025-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_default_home",
            field=models.BooleanField(
                default=False,
                help_text="このチームをホーム（運営）チームとして扱う場合にチェック",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="location",
            field=models.CharField(default="北海道", max_length=100),
            preserve_default=False,
        ),
    ]
