# Generated by Django 5.2.8 on 2025-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_is_default_home_alter_team_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="is_default_home",
        ),
        migrations.AddField(
            model_name="team",
            name="is_home_team",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
