# Generated by Django 5.2.8 on 2025-11-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_remove_team_is_default_home_team_is_home_team_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "チーム", "verbose_name_plural": "チーム一覧"},
        ),
    ]
