# Generated by Django 5.2.8 on 2025-11-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField(default=1)),
                (
                    "top_bottom",
                    models.CharField(
                        choices=[("top", "表"), ("bottom", "裏")], max_length=6
                    ),
                ),
                ("batting_order", models.PositiveSmallIntegerField()),
                (
                    "atbat_result",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "pitch_result",
                    models.CharField(
                        choices=[
                            ("ball", "ボール"),
                            ("strike", "ストライク"),
                            ("foul", "ファウル"),
                            ("inplay", "インプレー"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pitch_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catcher_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="center_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="first_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="games.game",
                    ),
                ),
                (
                    "hitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hitter_pitches",
                        to="games.lineup",
                    ),
                ),
                (
                    "left",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pitcher_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "runner_1b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="on_first",
                        to="players.player",
                    ),
                ),
                (
                    "runner_2b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="on_second",
                        to="players.player",
                    ),
                ),
                (
                    "runner_3b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="on_third",
                        to="players.player",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="second_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "short",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="short_pitches",
                        to="players.player",
                    ),
                ),
                (
                    "third",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="third_pitches",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "スコア",
                "verbose_name_plural": "スコア一覧",
                "ordering": ["game", "inning", "pitch_number"],
            },
        ),
    ]
