# Generated by Django 5.2.8 on 2025-11-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_lineup_options_alter_lineup_batting_order_and_more"),
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batting_order", models.PositiveSmallIntegerField()),
                (
                    "pitch_result",
                    models.CharField(
                        choices=[
                            ("ball", "ボール"),
                            ("strike", "ストライク"),
                            ("foul", "ファウル"),
                            ("inplay", "インプレー"),
                            ("hit", "ヒット"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "atbat_result",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pitch_number", models.PositiveIntegerField()),
                ("inning", models.PositiveIntegerField(default=1)),
                (
                    "top_bottom",
                    models.CharField(
                        choices=[("top", "表"), ("bottom", "裏")], max_length=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="games.game",
                    ),
                ),
                (
                    "hitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pitches",
                        to="games.lineup",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "inning", "pitch_number"],
            },
        ),
        migrations.DeleteModel(
            name="Game",
        ),
    ]
