# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pitch",
            options={"ordering": ["game", "inning", "pitch_number"]},
        ),
    ]
