# Generated by Django 5.2.8 on 2025-11-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_options_alter_inning_options_and_more"),
        ("scores", "0002_pitch_delete_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitch",
            name="hitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.lineup",
            ),
        ),
    ]
